<?php
// classmap.php - Autogenerated by Photon build.
// Do not edit!

$PHOTON__classmap = array (
  'Http404Controller' => 'app/Http404Controller.php',
  'IndexController' => 'app/IndexController.php',
  'Bootstrapper' => 'lib/Bootstrapper.php',
  'ClassLoader' => 'lib/ClassLoader.php',
  'InvariantViolationException' => 'lib/InvariantViolationException.php',
  'Photon' => 'lib/Photon.php',
  'Request' => 'lib/Request.php',
);